Module timers
    Public Sub timettempo()
        If Form1.ComboBox1.Text = "all" Then
            Form1.Timer1.Interval = Form1.TextBox1.Text
            Form1.time1.Text = Form1.Timer1.Interval / 1000 & " s"
            Form1.Timer2.Interval = Form1.TextBox1.Text
            Form1.time2.Text = Form1.Timer2.Interval / 1000 & " s"
            Form1.Timer3.Interval = Form1.TextBox1.Text
            Form1.time3.Text = Form1.Timer3.Interval / 1000 & " s"
            Form1.Timer4.Interval = Form1.TextBox1.Text
            Form1.time4.Text = Form1.Timer4.Interval / 1000 & " s"
            Form1.Timer5.Interval = Form1.TextBox1.Text
            Form1.time5.Text = Form1.Timer5.Interval / 1000 & " s"
            Form1.Timer6.Interval = Form1.TextBox1.Text
            Form1.time6.Text = Form1.Timer6.Interval / 1000 & " s"
            Form1.Timer7.Interval = Form1.TextBox1.Text
            Form1.time7.Text = Form1.Timer7.Interval / 1000 & " s"
            Form1.Timer8.Interval = Form1.TextBox1.Text
            Form1.time8.Text = Form1.Timer8.Interval / 1000 & " s"
            Form1.Timer9.Interval = Form1.TextBox1.Text
            Form1.time9.Text = Form1.Timer9.Interval / 1000 & " s"
            Form1.Timer10.Interval = Form1.TextBox1.Text
            Form1.time10.Text = Form1.Timer10.Interval / 1000 & " s"
            Form1.Timer11.Interval = Form1.TextBox1.Text
            Form1.time11.Text = Form1.Timer11.Interval / 1000 & " s"
            Form1.Timer12.Interval = Form1.TextBox1.Text
            Form1.time12.Text = Form1.Timer12.Interval / 1000 & " s"
            Form1.Timer13.Interval = Form1.TextBox1.Text
            Form1.time13.Text = Form1.Timer13.Interval / 1000 & " s"
            Form1.Timer14.Interval = Form1.TextBox1.Text
            Form1.time14.Text = Form1.Timer14.Interval / 1000 & " s"
            Form1.Timer15.Interval = Form1.TextBox1.Text
            Form1.time15.Text = Form1.Timer15.Interval / 1000 & " s"
            Form1.Timer16.Interval = Form1.TextBox1.Text
            Form1.time16.Text = Form1.Timer16.Interval / 1000 & " s"
            Form1.Timer17.Interval = Form1.TextBox1.Text
            Form1.time17.Text = Form1.Timer17.Interval / 1000 & " s"
            Form1.Timer18.Interval = Form1.TextBox1.Text
            Form1.time18.Text = Form1.Timer18.Interval / 1000 & " s"
            Form1.Timer19.Interval = Form1.TextBox1.Text
            Form1.time19.Text = Form1.Timer19.Interval / 1000 & " s"
            Form1.Timer20.Interval = Form1.TextBox1.Text
            Form1.time20.Text = Form1.Timer20.Interval / 1000 & " s"
            Form1.Timer21.Interval = Form1.TextBox1.Text
            Form1.time21.Text = Form1.Timer21.Interval / 1000 & " s"
            Form1.Timer22.Interval = Form1.TextBox1.Text
            Form1.time22.Text = Form1.Timer22.Interval / 1000 & " s"
            Form1.Timer23.Interval = Form1.TextBox1.Text
            Form1.time23.Text = Form1.Timer23.Interval / 1000 & " s"
            Form1.Timer24.Interval = Form1.TextBox1.Text
            Form1.time24.Text = Form1.Timer24.Interval / 1000 & " s"
            Form1.Timer25.Interval = Form1.TextBox1.Text
            Form1.time25.Text = Form1.Timer25.Interval / 1000 & " s"
            Form1.Timer26.Interval = Form1.TextBox1.Text
            Form1.time26.Text = Form1.Timer26.Interval / 1000 & " s"
            Form1.Timer27.Interval = Form1.TextBox1.Text
            Form1.time27.Text = Form1.Timer27.Interval / 1000 & " s"
            Form1.Timer28.Interval = Form1.TextBox1.Text
            Form1.time28.Text = Form1.Timer28.Interval / 1000 & " s"
            Form1.Timer29.Interval = Form1.TextBox1.Text
            Form1.time29.Text = Form1.Timer29.Interval / 1000 & " s"
            Form1.Timer30.Interval = Form1.TextBox1.Text
            Form1.time30.Text = Form1.Timer30.Interval / 1000 & " s"
            Form1.Timer31.Interval = Form1.TextBox1.Text
            Form1.time31.Text = Form1.Timer31.Interval / 1000 & " s"
            Form1.Timer32.Interval = Form1.TextBox1.Text
            Form1.time32.Text = Form1.Timer32.Interval / 1000 & " s"
            Form1.Timer33.Interval = Form1.TextBox1.Text
            Form1.time33.Text = Form1.Timer33.Interval / 1000 & " s"
            Form1.Timer34.Interval = Form1.TextBox1.Text
            Form1.time34.Text = Form1.Timer34.Interval / 1000 & " s"
            Form1.Timer35.Interval = Form1.TextBox1.Text
            Form1.time35.Text = Form1.Timer35.Interval / 1000 & " s"
            Form1.Timer36.Interval = Form1.TextBox1.Text
            Form1.time36.Text = Form1.Timer36.Interval / 1000 & " s"
            Form1.Timer37.Interval = Form1.TextBox1.Text
            Form1.time37.Text = Form1.Timer37.Interval / 1000 & " s"
            Form1.Timer38.Interval = Form1.TextBox1.Text
            Form1.time38.Text = Form1.Timer38.Interval / 1000 & " s"
            Form1.Timer39.Interval = Form1.TextBox1.Text
            Form1.time39.Text = Form1.Timer39.Interval / 1000 & " s"
            Form1.Timer40.Interval = Form1.TextBox1.Text
            Form1.time40.Text = Form1.Timer40.Interval / 1000 & " s"
            Form1.Timer41.Interval = Form1.TextBox1.Text
            Form1.time41.Text = Form1.Timer41.Interval / 1000 & " s"
            Form1.Timer42.Interval = Form1.TextBox1.Text
            Form1.time42.Text = Form1.Timer42.Interval / 1000 & " s"
            Form1.Timer43.Interval = Form1.TextBox1.Text
            Form1.time43.Text = Form1.Timer43.Interval / 1000 & " s"
            Form1.Timer44.Interval = Form1.TextBox1.Text
            Form1.time44.Text = Form1.Timer44.Interval / 1000 & " s"
            Form1.Timer45.Interval = Form1.TextBox1.Text
            Form1.time45.Text = Form1.Timer45.Interval / 1000 & " s"
            Form1.Timer46.Interval = Form1.TextBox1.Text
            Form1.time46.Text = Form1.Timer46.Interval / 1000 & " s"
            Form1.Timer47.Interval = Form1.TextBox1.Text
            Form1.time47.Text = Form1.Timer47.Interval / 1000 & " s"
            Form1.Timer48.Interval = Form1.TextBox1.Text
            Form1.time48.Text = Form1.Timer48.Interval / 1000 & " s"
            Form1.Timer49.Interval = Form1.TextBox1.Text
            Form1.time49.Text = Form1.Timer49.Interval / 1000 & " s"
            Form1.Timer50.Interval = Form1.TextBox1.Text
            Form1.time50.Text = Form1.Timer50.Interval / 1000 & " s"
            Form1.Timer51.Interval = Form1.TextBox1.Text
            Form1.time51.Text = Form1.Timer51.Interval / 1000 & " s"
            Form1.Timer52.Interval = Form1.TextBox1.Text
            Form1.time52.Text = Form1.Timer52.Interval / 1000 & " s"
            Form1.Timer53.Interval = Form1.TextBox1.Text
            Form1.time53.Text = Form1.Timer53.Interval / 1000 & " s"
            Form1.Timer54.Interval = Form1.TextBox1.Text
            Form1.time54.Text = Form1.Timer54.Interval / 1000 & " s"
            Form1.Timer55.Interval = Form1.TextBox1.Text
            Form1.time55.Text = Form1.Timer55.Interval / 1000 & " s"
            Form1.Timer56.Interval = Form1.TextBox1.Text
            Form1.time56.Text = Form1.Timer56.Interval / 1000 & " s"
            Form1.Timer57.Interval = Form1.TextBox1.Text
            Form1.time57.Text = Form1.Timer57.Interval / 1000 & " s"
            Form1.Timer58.Interval = Form1.TextBox1.Text
            Form1.time58.Text = Form1.Timer58.Interval / 1000 & " s"
            Form1.Timer59.Interval = Form1.TextBox1.Text
            Form1.time59.Text = Form1.Timer59.Interval / 1000 & " s"
            Form1.Timer60.Interval = Form1.TextBox1.Text
            Form1.time60.Text = Form1.Timer60.Interval / 1000 & " s"
            Form1.Timer61.Interval = Form1.TextBox1.Text
            Form1.time61.Text = Form1.Timer61.Interval / 1000 & " s"
            Form1.Timer62.Interval = Form1.TextBox1.Text
            Form1.time62.Text = Form1.Timer62.Interval / 1000 & " s"
            Form1.Timer63.Interval = Form1.TextBox1.Text
            Form1.time63.Text = Form1.Timer63.Interval / 1000 & " s"
            Form1.Timer64.Interval = Form1.TextBox1.Text
            Form1.time64.Text = Form1.Timer64.Interval / 1000 & " s"
            Form1.Timer65.Interval = Form1.TextBox1.Text
            Form1.time65.Text = Form1.Timer65.Interval / 1000 & " s"
            Form1.Timer66.Interval = Form1.TextBox1.Text
            Form1.time66.Text = Form1.Timer66.Interval / 1000 & " s"
            Form1.Timer67.Interval = Form1.TextBox1.Text
            Form1.time67.Text = Form1.Timer67.Interval / 1000 & " s"
            Form1.Timer68.Interval = Form1.TextBox1.Text
            Form1.time68.Text = Form1.Timer68.Interval / 1000 & " s"
            Form1.Timer69.Interval = Form1.TextBox1.Text
            Form1.time69.Text = Form1.Timer69.Interval / 1000 & " s"
            Form1.Timer70.Interval = Form1.TextBox1.Text
            Form1.time70.Text = Form1.Timer70.Interval / 1000 & " s"
            Form1.Timer71.Interval = Form1.TextBox1.Text
            Form1.time71.Text = Form1.Timer71.Interval / 1000 & " s"
            Form1.Timer72.Interval = Form1.TextBox1.Text
            Form1.time72.Text = Form1.Timer72.Interval / 1000 & " s"
            Form1.Timer73.Interval = Form1.TextBox1.Text
            Form1.time73.Text = Form1.Timer73.Interval / 1000 & " s"
            Form1.Timer74.Interval = Form1.TextBox1.Text
            Form1.time74.Text = Form1.Timer74.Interval / 1000 & " s"
            Form1.Timer75.Interval = Form1.TextBox1.Text
            Form1.time75.Text = Form1.Timer75.Interval / 1000 & " s"
            Form1.Timer76.Interval = Form1.TextBox1.Text
            Form1.time76.Text = Form1.Timer76.Interval / 1000 & " s"
            Form1.Timer77.Interval = Form1.TextBox1.Text
            Form1.time77.Text = Form1.Timer77.Interval / 1000 & " s"
            Form1.Timer78.Interval = Form1.TextBox1.Text
            Form1.time78.Text = Form1.Timer78.Interval / 1000 & " s"
            Form1.Timer79.Interval = Form1.TextBox1.Text
            Form1.time79.Text = Form1.Timer79.Interval / 1000 & " s"
            Form1.Timer80.Interval = Form1.TextBox1.Text
            Form1.time80.Text = Form1.Timer80.Interval / 1000 & " s"
            Form1.Timer81.Interval = Form1.TextBox1.Text
            Form1.time81.Text = Form1.Timer81.Interval / 1000 & " s"
            Form1.Timer82.Interval = Form1.TextBox1.Text
            Form1.time82.Text = Form1.Timer82.Interval / 1000 & " s"
            Form1.Timer83.Interval = Form1.TextBox1.Text
            Form1.time83.Text = Form1.Timer83.Interval / 1000 & " s"
            Form1.Timer84.Interval = Form1.TextBox1.Text
            Form1.time84.Text = Form1.Timer84.Interval / 1000 & " s"
            Form1.Timer85.Interval = Form1.TextBox1.Text
            Form1.time85.Text = Form1.Timer85.Interval / 1000 & " s"
            Form1.Timer86.Interval = Form1.TextBox1.Text
            Form1.time86.Text = Form1.Timer86.Interval / 1000 & " s"
            Form1.Timer87.Interval = Form1.TextBox1.Text
            Form1.time87.Text = Form1.Timer87.Interval / 1000 & " s"
            Form1.Timer88.Interval = Form1.TextBox1.Text
            Form1.time88.Text = Form1.Timer88.Interval / 1000 & " s"
            Form1.Timer89.Interval = Form1.TextBox1.Text
            Form1.time89.Text = Form1.Timer89.Interval / 1000 & " s"
            Form1.Timer90.Interval = Form1.TextBox1.Text
            Form1.time90.Text = Form1.Timer90.Interval / 1000 & " s"
            Form1.Timer91.Interval = Form1.TextBox1.Text
            Form1.time91.Text = Form1.Timer91.Interval / 1000 & " s"
            Form1.Timer92.Interval = Form1.TextBox1.Text
            Form1.time92.Text = Form1.Timer92.Interval / 1000 & " s"
            Form1.Timer93.Interval = Form1.TextBox1.Text
            Form1.time93.Text = Form1.Timer93.Interval / 1000 & " s"
            Form1.Timer94.Interval = Form1.TextBox1.Text
            Form1.time94.Text = Form1.Timer94.Interval / 1000 & " s"
            Form1.Timer95.Interval = Form1.TextBox1.Text
            Form1.time95.Text = Form1.Timer95.Interval / 1000 & " s"
            Form1.Timer96.Interval = Form1.TextBox1.Text
            Form1.time96.Text = Form1.Timer96.Interval / 1000 & " s"
            Form1.Timer97.Interval = Form1.TextBox1.Text
            Form1.time97.Text = Form1.Timer97.Interval / 1000 & " s"
            Form1.Timer98.Interval = Form1.TextBox1.Text
            Form1.time98.Text = Form1.Timer98.Interval / 1000 & " s"
            Form1.Timer99.Interval = Form1.TextBox1.Text
            Form1.time99.Text = Form1.Timer99.Interval / 1000 & " s"
            Form1.Timer100.Interval = Form1.TextBox1.Text
            Form1.time100.Text = Form1.Timer100.Interval / 1000 & " s"


        ElseIf Form1.ComboBox1.Text = "L1" Then
            Form1.Timer1.Interval = Form1.TextBox1.Text
            Form1.time1.Text = Form1.Timer1.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L2" Then
            Form1.Timer2.Interval = Form1.TextBox1.Text
            Form1.time2.Text = Form1.Timer2.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L3" Then
            Form1.Timer3.Interval = Form1.TextBox1.Text
            Form1.time3.Text = Form1.Timer3.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L4" Then
            Form1.Timer4.Interval = Form1.TextBox1.Text
            Form1.time4.Text = Form1.Timer4.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L5" Then
            Form1.Timer5.Interval = Form1.TextBox1.Text
            Form1.time5.Text = Form1.Timer5.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L6" Then
            Form1.Timer6.Interval = Form1.TextBox1.Text
            Form1.time6.Text = Form1.Timer6.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L7" Then
            Form1.Timer7.Interval = Form1.TextBox1.Text
            Form1.time7.Text = Form1.Timer7.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L8" Then
            Form1.Timer8.Interval = Form1.TextBox1.Text
            Form1.time8.Text = Form1.Timer8.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L9" Then
            Form1.Timer9.Interval = Form1.TextBox1.Text
            Form1.time9.Text = Form1.Timer9.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L10" Then
            Form1.Timer10.Interval = Form1.TextBox1.Text
            Form1.time10.Text = Form1.Timer10.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L11" Then
            Form1.Timer11.Interval = Form1.TextBox1.Text
            Form1.time11.Text = Form1.Timer11.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L12" Then
            Form1.Timer12.Interval = Form1.TextBox1.Text
            Form1.time12.Text = Form1.Timer12.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L13" Then
            Form1.Timer13.Interval = Form1.TextBox1.Text
            Form1.time13.Text = Form1.Timer13.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L14" Then
            Form1.Timer14.Interval = Form1.TextBox1.Text
            Form1.time14.Text = Form1.Timer14.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L15" Then
            Form1.Timer15.Interval = Form1.TextBox1.Text
            Form1.time15.Text = Form1.Timer15.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L16" Then
            Form1.Timer16.Interval = Form1.TextBox1.Text
            Form1.time16.Text = Form1.Timer16.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L17" Then
            Form1.Timer17.Interval = Form1.TextBox1.Text
            Form1.time17.Text = Form1.Timer17.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L18" Then
            Form1.Timer18.Interval = Form1.TextBox1.Text
            Form1.time18.Text = Form1.Timer18.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L19" Then
            Form1.Timer19.Interval = Form1.TextBox1.Text
            Form1.time19.Text = Form1.Timer19.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L20" Then
            Form1.Timer20.Interval = Form1.TextBox1.Text
            Form1.time20.Text = Form1.Timer20.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L21" Then
            Form1.Timer21.Interval = Form1.TextBox1.Text
            Form1.time21.Text = Form1.Timer21.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L22" Then
            Form1.Timer22.Interval = Form1.TextBox1.Text
            Form1.time22.Text = Form1.Timer22.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L23" Then
            Form1.Timer23.Interval = Form1.TextBox1.Text
            Form1.time23.Text = Form1.Timer23.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L24" Then
            Form1.Timer24.Interval = Form1.TextBox1.Text
            Form1.time24.Text = Form1.Timer24.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L25" Then
            Form1.Timer25.Interval = Form1.TextBox1.Text
            Form1.time25.Text = Form1.Timer25.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L26" Then
            Form1.Timer26.Interval = Form1.TextBox1.Text
            Form1.time26.Text = Form1.Timer26.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L27" Then
            Form1.Timer27.Interval = Form1.TextBox1.Text
            Form1.time27.Text = Form1.Timer27.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L28" Then
            Form1.Timer28.Interval = Form1.TextBox1.Text
            Form1.time28.Text = Form1.Timer28.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L29" Then
            Form1.Timer29.Interval = Form1.TextBox1.Text
            Form1.time29.Text = Form1.Timer29.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L30" Then
            Form1.Timer30.Interval = Form1.TextBox1.Text
            Form1.time30.Text = Form1.Timer30.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L31" Then
            Form1.Timer31.Interval = Form1.TextBox1.Text
            Form1.time31.Text = Form1.Timer31.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L32" Then
            Form1.Timer32.Interval = Form1.TextBox1.Text
            Form1.time32.Text = Form1.Timer32.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L33" Then
            Form1.Timer33.Interval = Form1.TextBox1.Text
            Form1.time33.Text = Form1.Timer33.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L34" Then
            Form1.Timer34.Interval = Form1.TextBox1.Text
            Form1.time34.Text = Form1.Timer34.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L35" Then
            Form1.Timer35.Interval = Form1.TextBox1.Text
            Form1.time35.Text = Form1.Timer35.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L36" Then
            Form1.Timer36.Interval = Form1.TextBox1.Text
            Form1.time36.Text = Form1.Timer36.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L37" Then
            Form1.Timer37.Interval = Form1.TextBox1.Text
            Form1.time37.Text = Form1.Timer37.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L38" Then
            Form1.Timer38.Interval = Form1.TextBox1.Text
            Form1.time38.Text = Form1.Timer38.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L39" Then
            Form1.Timer39.Interval = Form1.TextBox1.Text
            Form1.time39.Text = Form1.Timer39.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L40" Then
            Form1.Timer40.Interval = Form1.TextBox1.Text
            Form1.time40.Text = Form1.Timer40.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L41" Then
            Form1.Timer41.Interval = Form1.TextBox1.Text
            Form1.time41.Text = Form1.Timer41.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L42" Then
            Form1.Timer42.Interval = Form1.TextBox1.Text
            Form1.time42.Text = Form1.Timer42.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L43" Then
            Form1.Timer43.Interval = Form1.TextBox1.Text
            Form1.time43.Text = Form1.Timer43.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L44" Then
            Form1.Timer44.Interval = Form1.TextBox1.Text
            Form1.time44.Text = Form1.Timer44.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L45" Then
            Form1.Timer45.Interval = Form1.TextBox1.Text
            Form1.time45.Text = Form1.Timer45.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L46" Then
            Form1.Timer46.Interval = Form1.TextBox1.Text
            Form1.time46.Text = Form1.Timer46.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L47" Then
            Form1.Timer47.Interval = Form1.TextBox1.Text
            Form1.time47.Text = Form1.Timer47.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L48" Then
            Form1.Timer48.Interval = Form1.TextBox1.Text
            Form1.time48.Text = Form1.Timer48.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L49" Then
            Form1.Timer49.Interval = Form1.TextBox1.Text
            Form1.time49.Text = Form1.Timer49.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L50" Then
            Form1.Timer50.Interval = Form1.TextBox1.Text
            Form1.time50.Text = Form1.Timer50.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L51" Then
            Form1.Timer51.Interval = Form1.TextBox1.Text
            Form1.time51.Text = Form1.Timer51.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L52" Then
            Form1.Timer52.Interval = Form1.TextBox1.Text
            Form1.time52.Text = Form1.Timer52.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L53" Then
            Form1.Timer53.Interval = Form1.TextBox1.Text
            Form1.time53.Text = Form1.Timer53.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L54" Then
            Form1.Timer54.Interval = Form1.TextBox1.Text
            Form1.time54.Text = Form1.Timer54.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L55" Then
            Form1.Timer55.Interval = Form1.TextBox1.Text
            Form1.time55.Text = Form1.Timer55.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L56" Then
            Form1.Timer56.Interval = Form1.TextBox1.Text
            Form1.time56.Text = Form1.Timer56.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L57" Then
            Form1.Timer57.Interval = Form1.TextBox1.Text
            Form1.time57.Text = Form1.Timer57.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L58" Then
            Form1.Timer58.Interval = Form1.TextBox1.Text
            Form1.time58.Text = Form1.Timer58.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L59" Then
            Form1.Timer59.Interval = Form1.TextBox1.Text
            Form1.time59.Text = Form1.Timer59.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L60" Then
            Form1.Timer60.Interval = Form1.TextBox1.Text
            Form1.time60.Text = Form1.Timer60.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L61" Then
            Form1.Timer61.Interval = Form1.TextBox1.Text
            Form1.time61.Text = Form1.Timer61.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L62" Then
            Form1.Timer62.Interval = Form1.TextBox1.Text
            Form1.time62.Text = Form1.Timer62.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L63" Then
            Form1.Timer63.Interval = Form1.TextBox1.Text
            Form1.time63.Text = Form1.Timer63.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L64" Then
            Form1.Timer64.Interval = Form1.TextBox1.Text
            Form1.time64.Text = Form1.Timer64.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L65" Then
            Form1.Timer65.Interval = Form1.TextBox1.Text
            Form1.time65.Text = Form1.Timer65.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L66" Then
            Form1.Timer66.Interval = Form1.TextBox1.Text
            Form1.time66.Text = Form1.Timer66.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L67" Then
            Form1.Timer67.Interval = Form1.TextBox1.Text
            Form1.time67.Text = Form1.Timer67.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L68" Then
            Form1.Timer68.Interval = Form1.TextBox1.Text
            Form1.time68.Text = Form1.Timer68.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L69" Then
            Form1.Timer69.Interval = Form1.TextBox1.Text
            Form1.time69.Text = Form1.Timer69.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L70" Then
            Form1.Timer70.Interval = Form1.TextBox1.Text
            Form1.time70.Text = Form1.Timer70.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L71" Then
            Form1.Timer71.Interval = Form1.TextBox1.Text
            Form1.time71.Text = Form1.Timer71.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L72" Then
            Form1.Timer72.Interval = Form1.TextBox1.Text
            Form1.time72.Text = Form1.Timer72.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L73" Then
            Form1.Timer73.Interval = Form1.TextBox1.Text
            Form1.time73.Text = Form1.Timer73.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L74" Then
            Form1.Timer74.Interval = Form1.TextBox1.Text
            Form1.time74.Text = Form1.Timer74.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L75" Then
            Form1.Timer75.Interval = Form1.TextBox1.Text
            Form1.time75.Text = Form1.Timer75.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L76" Then
            Form1.Timer76.Interval = Form1.TextBox1.Text
            Form1.time76.Text = Form1.Timer76.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L77" Then
            Form1.Timer77.Interval = Form1.TextBox1.Text
            Form1.time77.Text = Form1.Timer77.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L78" Then
            Form1.Timer78.Interval = Form1.TextBox1.Text
            Form1.time78.Text = Form1.Timer78.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L79" Then
            Form1.Timer79.Interval = Form1.TextBox1.Text
            Form1.time79.Text = Form1.Timer79.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L80" Then
            Form1.Timer80.Interval = Form1.TextBox1.Text
            Form1.time80.Text = Form1.Timer80.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L81" Then
            Form1.Timer81.Interval = Form1.TextBox1.Text
            Form1.time81.Text = Form1.Timer81.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L82" Then
            Form1.Timer82.Interval = Form1.TextBox1.Text
            Form1.time82.Text = Form1.Timer82.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L83" Then
            Form1.Timer83.Interval = Form1.TextBox1.Text
            Form1.time83.Text = Form1.Timer83.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L84" Then
            Form1.Timer84.Interval = Form1.TextBox1.Text
            Form1.time84.Text = Form1.Timer84.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L85" Then
            Form1.Timer85.Interval = Form1.TextBox1.Text
            Form1.time85.Text = Form1.Timer85.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L86" Then
            Form1.Timer86.Interval = Form1.TextBox1.Text
            Form1.time86.Text = Form1.Timer86.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L87" Then
            Form1.Timer87.Interval = Form1.TextBox1.Text
            Form1.time87.Text = Form1.Timer87.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L88" Then
            Form1.Timer88.Interval = Form1.TextBox1.Text
            Form1.time88.Text = Form1.Timer88.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L89" Then
            Form1.Timer89.Interval = Form1.TextBox1.Text
            Form1.time89.Text = Form1.Timer89.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L90" Then
            Form1.Timer90.Interval = Form1.TextBox1.Text
            Form1.time90.Text = Form1.Timer90.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L91" Then
            Form1.Timer91.Interval = Form1.TextBox1.Text
            Form1.time91.Text = Form1.Timer91.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L92" Then
            Form1.Timer92.Interval = Form1.TextBox1.Text
            Form1.time92.Text = Form1.Timer92.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L93" Then
            Form1.Timer93.Interval = Form1.TextBox1.Text
            Form1.time93.Text = Form1.Timer93.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L94" Then
            Form1.Timer94.Interval = Form1.TextBox1.Text
            Form1.time94.Text = Form1.Timer94.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L95" Then
            Form1.Timer95.Interval = Form1.TextBox1.Text
            Form1.time95.Text = Form1.Timer95.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L96" Then
            Form1.Timer96.Interval = Form1.TextBox1.Text
            Form1.time96.Text = Form1.Timer96.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L97" Then
            Form1.Timer97.Interval = Form1.TextBox1.Text
            Form1.time97.Text = Form1.Timer97.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L98" Then
            Form1.Timer98.Interval = Form1.TextBox1.Text
            Form1.time98.Text = Form1.Timer98.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L99" Then
            Form1.Timer99.Interval = Form1.TextBox1.Text
            Form1.time99.Text = Form1.Timer99.Interval / 1000 & " s"
        ElseIf Form1.ComboBox1.Text = "L100" Then
            Form1.Timer100.Interval = Form1.TextBox1.Text
            Form1.time100.Text = Form1.Timer100.Interval / 1000 & " s"
        End If
    End Sub
    Public Sub timerpassescritor()
        If Form1.timerpass.Text = "0" Then
            Form1.xiin = 0
            timerstop()
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "1" Then
            Form1.Timer2.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "2" Then
            Form1.Timer3.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "3" Then
            Form1.Timer4.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "4" Then
            Form1.Timer5.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "5" Then
            Form1.Timer6.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "6" Then
            Form1.Timer7.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "7" Then
            Form1.Timer8.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "8" Then
            Form1.Timer9.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "9" Then
            Form1.Timer10.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "10" Then
            Form1.Timer11.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "11" Then
            Form1.Timer12.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "12" Then
            Form1.Timer13.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "13" Then
            Form1.Timer14.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "14" Then
            Form1.Timer15.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "15" Then
            Form1.Timer16.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "16" Then
            Form1.Timer17.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "17" Then
            Form1.Timer18.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "18" Then
            Form1.Timer19.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "19" Then
            Form1.Timer20.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "20" Then
            Form1.Timer21.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "21" Then
            Form1.Timer22.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "22" Then
            Form1.Timer23.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "23" Then
            Form1.Timer24.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "24" Then
            Form1.Timer25.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "25" Then
            Form1.Timer26.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "26" Then
            Form1.Timer27.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "27" Then
            Form1.Timer28.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "28" Then
            Form1.Timer29.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "29" Then
            Form1.Timer30.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "30" Then
            Form1.Timer31.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "31" Then
            Form1.Timer32.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "32" Then
            Form1.Timer33.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "33" Then
            Form1.Timer34.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "34" Then
            Form1.Timer35.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "35" Then
            Form1.Timer36.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "36" Then
            Form1.Timer37.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "37" Then
            Form1.Timer38.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "38" Then
            Form1.Timer39.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "39" Then
            Form1.Timer40.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "40" Then
            Form1.Timer41.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "41" Then
            Form1.Timer42.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "42" Then
            Form1.Timer43.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "43" Then
            Form1.Timer44.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "44" Then
            Form1.Timer45.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "45" Then
            Form1.Timer46.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "46" Then
            Form1.Timer47.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "47" Then
            Form1.Timer48.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "48" Then
            Form1.Timer49.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "49" Then
            Form1.Timer50.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "50" Then
            Form1.Timer51.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "51" Then
            Form1.Timer52.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "52" Then
            Form1.Timer53.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "53" Then
            Form1.Timer54.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "54" Then
            Form1.Timer55.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "55" Then
            Form1.Timer56.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "56" Then
            Form1.Timer57.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "57" Then
            Form1.Timer58.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "58" Then
            Form1.Timer59.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "59" Then
            Form1.Timer60.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "60" Then
            Form1.Timer61.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "61" Then
            Form1.Timer62.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "62" Then
            Form1.Timer63.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "63" Then
            Form1.Timer64.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "64" Then
            Form1.Timer65.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "65" Then
            Form1.Timer66.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "66" Then
            Form1.Timer67.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "67" Then
            Form1.Timer68.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "68" Then
            Form1.Timer69.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "69" Then
            Form1.Timer70.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "70" Then
            Form1.Timer71.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "71" Then
            Form1.Timer72.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "72" Then
            Form1.Timer73.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "73" Then
            Form1.Timer74.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "74" Then
            Form1.Timer75.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "75" Then
            Form1.Timer76.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "76" Then
            Form1.Timer77.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "77" Then
            Form1.Timer78.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "78" Then
            Form1.Timer79.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "79" Then
            Form1.Timer80.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "80" Then
            Form1.Timer81.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "81" Then
            Form1.Timer82.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "82" Then
            Form1.Timer83.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "83" Then
            Form1.Timer84.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "84" Then
            Form1.Timer85.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "85" Then
            Form1.Timer86.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "86" Then
            Form1.Timer87.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "87" Then
            Form1.Timer88.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "88" Then
            Form1.Timer89.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "89" Then
            Form1.Timer90.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "90" Then
            Form1.Timer91.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "91" Then
            Form1.Timer92.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "92" Then
            Form1.Timer93.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "93" Then
            Form1.Timer94.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "94" Then
            Form1.Timer95.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "95" Then
            Form1.Timer96.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "96" Then
            Form1.Timer97.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "97" Then
            Form1.Timer98.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "98" Then
            Form1.Timer99.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "99" Then
            Form1.Timer100.Enabled = True
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
        ElseIf Form1.timerpass.Text = "100" Then
            Form1.xiin = 0
            Form1.Escritor.Enabled = False
       
        End If
    End Sub
    Public Sub timerstop()
        Form1.program.Enabled = False
        Form1.Escritor.Enabled = False
        Form1.Timer1.Enabled = False
        Form1.Timer2.Enabled = False
        Form1.Timer3.Enabled = False
        Form1.Timer4.Enabled = False
        Form1.Timer5.Enabled = False
        Form1.Timer6.Enabled = False
        Form1.Timer7.Enabled = False
        Form1.Timer8.Enabled = False
        Form1.Timer9.Enabled = False
        Form1.Timer10.Enabled = False
        Form1.Timer11.Enabled = False
        Form1.Timer12.Enabled = False
        Form1.Timer13.Enabled = False
        Form1.Timer14.Enabled = False
        Form1.Timer15.Enabled = False
        Form1.Timer16.Enabled = False
        Form1.Timer17.Enabled = False
        Form1.Timer18.Enabled = False
        Form1.Timer19.Enabled = False
        Form1.Timer20.Enabled = False
        Form1.Timer21.Enabled = False
        Form1.Timer22.Enabled = False
        Form1.Timer23.Enabled = False
        Form1.Timer24.Enabled = False
        Form1.Timer25.Enabled = False
        Form1.Timer26.Enabled = False
        Form1.Timer27.Enabled = False
        Form1.Timer28.Enabled = False
        Form1.Timer29.Enabled = False
        Form1.Timer30.Enabled = False
        Form1.Timer31.Enabled = False
        Form1.Timer32.Enabled = False
        Form1.Timer33.Enabled = False
        Form1.Timer34.Enabled = False
        Form1.Timer35.Enabled = False
        Form1.Timer36.Enabled = False
        Form1.Timer37.Enabled = False
        Form1.Timer38.Enabled = False
        Form1.Timer39.Enabled = False
        Form1.Timer40.Enabled = False
        Form1.Timer41.Enabled = False
        Form1.Timer42.Enabled = False
        Form1.Timer43.Enabled = False
        Form1.Timer44.Enabled = False
        Form1.Timer45.Enabled = False
        Form1.Timer46.Enabled = False
        Form1.Timer47.Enabled = False
        Form1.Timer48.Enabled = False
        Form1.Timer49.Enabled = False
        Form1.Timer50.Enabled = False
        Form1.Timer51.Enabled = False
        Form1.Timer52.Enabled = False
        Form1.Timer53.Enabled = False
        Form1.Timer54.Enabled = False
        Form1.Timer55.Enabled = False
        Form1.Timer56.Enabled = False
        Form1.Timer57.Enabled = False
        Form1.Timer58.Enabled = False
        Form1.Timer59.Enabled = False
        Form1.Timer60.Enabled = False
        Form1.Timer61.Enabled = False
        Form1.Timer62.Enabled = False
        Form1.Timer63.Enabled = False
        Form1.Timer64.Enabled = False
        Form1.Timer65.Enabled = False
        Form1.Timer66.Enabled = False
        Form1.Timer67.Enabled = False
        Form1.Timer68.Enabled = False
        Form1.Timer69.Enabled = False
        Form1.Timer70.Enabled = False
        Form1.Timer71.Enabled = False
        Form1.Timer72.Enabled = False
        Form1.Timer73.Enabled = False
        Form1.Timer74.Enabled = False
        Form1.Timer75.Enabled = False
        Form1.Timer76.Enabled = False
        Form1.Timer77.Enabled = False
        Form1.Timer78.Enabled = False
        Form1.Timer79.Enabled = False
        Form1.Timer80.Enabled = False
        Form1.Timer81.Enabled = False
        Form1.Timer82.Enabled = False
        Form1.Timer83.Enabled = False
        Form1.Timer84.Enabled = False
        Form1.Timer85.Enabled = False
        Form1.Timer86.Enabled = False
        Form1.Timer87.Enabled = False
        Form1.Timer88.Enabled = False
        Form1.Timer89.Enabled = False
        Form1.Timer90.Enabled = False
        Form1.Timer91.Enabled = False
        Form1.Timer92.Enabled = False
        Form1.Timer93.Enabled = False
        Form1.Timer94.Enabled = False
        Form1.Timer95.Enabled = False
        Form1.Timer96.Enabled = False
        Form1.Timer97.Enabled = False
        Form1.Timer98.Enabled = False
        Form1.Timer99.Enabled = False
        Form1.Timer100.Enabled = False
    End Sub
    Public Sub filterB()
        Dim bo1 As String
        Dim bo2 As String
        Dim bo3 As String
        Dim bo4 As String
        Dim bo5 As String
        Dim bo6 As String
        Dim bo7 As String
        Dim bo8 As String
        Dim to1 As String
        Dim to2 As String
        Dim to3 As String
        Dim to4 As String
        Dim to5 As String
        Dim to6 As String
        Dim to7 As String
        Dim to8 As String
        If InStr(Form1.baseT, "{") Then
            bo1 = Replace(Form1.baseT, "{", "°coder1°coder1°")
            Form1.Filter = bo1
        Else
            bo1 = Form1.baseT
            Form1.Filter = bo1
        End If
        If InStr(bo1, "}") Then
            bo2 = Replace(bo1, "}", "°coder2°coder2°")
            Form1.Filter = bo2
        Else
            bo2 = bo1
            Form1.Filter = bo2
        End If
        If InStr(bo2, "(") Then
            bo3 = Replace(bo2, "(", "°coder3°coder3°")
            Form1.Filter = bo3
        Else
            bo3 = bo2
            Form1.Filter = bo3
        End If
        If InStr(bo3, ")") Then
            bo4 = Replace(bo3, ")", "°coder4°coder4°")
            Form1.Filter = bo4
        Else
            bo4 = bo3
            Form1.Filter = bo4
        End If
        If InStr(bo4, "+") Then
            bo5 = Replace(bo4, "+", "°coder5°coder5°")
            Form1.Filter = bo5
        Else
            bo5 = bo4
            Form1.Filter = bo5
        End If
        If InStr(bo5, "^") Then
            bo6 = Replace(bo5, "^", "°coder6°coder6°")
            Form1.Filter = bo6
        Else
            bo6 = bo5
            Form1.Filter = bo6
        End If
        If InStr(bo6, "%") Then
            bo7 = Replace(bo6, "%", "°coder7°coder7°")
            Form1.Filter = bo7
        Else
            bo7 = bo6
            Form1.Filter = bo7
        End If
        If InStr(bo7, "~") Then
            bo8 = Replace(bo7, "~", "°coder8°coder8°")
            Form1.Filter = bo8
        Else
            bo8 = bo7
            Form1.Filter = bo8
        End If
        If InStr(Form1.Filter, "°coder1°coder1°") Then
            to1 = Replace(Form1.Filter, "°coder1°coder1°", "{{}")
            Form1.buffer = to1
        Else
            to1 = Form1.Filter
            Form1.buffer = to1
        End If
        If InStr(to1, "°coder2°coder2°") Then
            to2 = Replace(to1, "°coder2°coder2°", "{}}")
            Form1.buffer = to2
        Else
            to2 = to1
            Form1.buffer = to2
        End If
        If InStr(to2, "°coder3°coder3°") Then
            to3 = Replace(to2, "°coder3°coder3°", "{(}")
            Form1.buffer = to3
        Else
            to3 = to2
            Form1.buffer = to3
        End If
        If InStr(to3, "°coder4°coder4°") Then
            to4 = Replace(to3, "°coder4°coder4°", "{)}")
            Form1.buffer = to4
        Else
            to4 = to3
            Form1.buffer = to4
        End If
        If InStr(to4, "°coder5°coder5°") Then
            to5 = Replace(to4, "°coder5°coder5°", "{+}")
            Form1.buffer = to5
        Else
            to5 = to4
            Form1.buffer = to5
        End If
        If InStr(to5, "°coder6°coder6°") Then
            to6 = Replace(to5, "°coder6°coder6°", "{^}")
            Form1.buffer = to6
        Else
            to6 = to5
            Form1.buffer = to6
        End If
        If InStr(to6, "°coder7°coder7°") Then
            to7 = Replace(to6, "°coder7°coder7°", "{%}")
            Form1.buffer = to7
        Else
            to7 = to6
            Form1.buffer = to7
        End If
        If InStr(to7, "°coder8°coder8°") Then
            to8 = Replace(to7, "°coder8°coder8°", "{~}")
            Form1.buffer = to8
        End If
    End Sub
End Module
